export const assistantKeys = {
	all: (ws: string) => ['assistant', ws] as const,
	home: (ws: string) => ['assistant', ws, 'home'] as const,
	sessions: (ws: string) => ['assistant', ws, 'sessions'] as const,
	session: (ws: string, id: string) => ['assistant', ws, 'sessions', id] as const,
	messages: (ws: string, id: string) => ['assistant', ws, 'sessions', id, 'messages'] as const,
	context: (ws: string, id: string) => ['assistant', ws, 'sessions', id, 'context'] as const,
	memories: (ws: string) => ['assistant', ws, 'memories'] as const,
	styles: (ws: string) => ['assistant', ws, 'styles'] as const,
	daily: (ws: string) => ['assistant', ws, 'daily'] as const,
	meetingPrep: (ws: string) => ['assistant', ws, 'meeting-prep'] as const,
	meetings: (ws: string) => ['assistant', ws, 'meetings'] as const,
	briefingRun: (ws: string, id: string) => ['assistant', ws, 'briefing-runs', id] as const,
	situations: (ws: string, status: string) => ['assistant', ws, 'situations', status] as const,
	apps: (ws: string) => ['assistant', ws, 'apps'] as const,
	toolRules: (ws: string) => ['assistant', ws, 'tool-rules'] as const,
};
